<?php

namespace My\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AktorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AktorRepository extends EntityRepository
{
}
