<?php

namespace My\Frontend3Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Word2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Word2Repository extends EntityRepository
{
}
