<?php

namespace My\Frontend2Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MountainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MountainRepository extends EntityRepository
{
}
